# Generated by Django 2.2.6 on 2019-10-13 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191013_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappeningEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('poster', models.ImageField(upload_to='media/')),
                ('participants', jsonfield.fields.JSONField(default=dict)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=4096)),
                ('contact_number', models.CharField(max_length=15)),
                ('event_date', models.DateTimeField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myevents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
