# Generated by Django 2.2.6 on 2019-10-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_happeningevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happeningevents',
            name='event_date',
            field=models.CharField(max_length=30),
        ),
    ]
