# Generated by Django 2.2.6 on 2019-10-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191013_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningevents',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
