# Generated by Django 2.2.6 on 2019-11-19 07:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191119_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prime_interest',
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='happeningevents',
            name='type',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
